# Generated by Django 2.1.2 on 2018-10-21 01:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="O número de telefone deve estar no formato: '+999999999'. Até 15 dígitos são permitidos.", regex='^\\+?1?\\d{9,15}$')])),
            ],
            options={
                'verbose_name': 'Gerador',
                'verbose_name_plural': 'Geradores',
            },
        ),
        migrations.CreateModel(
            name='Waste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('unit', models.CharField(choices=[('Kg', 'Kilogramas'), ('L', 'Litros')], default='L', max_length=2)),
                ('chemical_makeup', models.CharField(max_length=200)),
                ('explosive', models.CharField(choices=[('Sim', 'SIM'), ('Não', 'NÃO'), ('Não Sei', 'NÃO SEI')], max_length=7)),
                ('flammable', models.CharField(choices=[('Sim', 'SIM'), ('Não', 'NÃO'), ('Não Sei', 'NÃO SEI')], max_length=7)),
                ('oxidizing', models.CharField(choices=[('Sim', 'SIM'), ('Não', 'NÃO'), ('Não Sei', 'NÃO SEI')], max_length=7)),
                ('under_pressure', models.CharField(choices=[('Sim', 'SIM'), ('Não', 'NÃO'), ('Não Sei', 'NÃO SEI')], max_length=7)),
                ('toxic', models.CharField(choices=[('Sim', 'SIM'), ('Não', 'NÃO'), ('Não Sei', 'NÃO SEI')], max_length=7)),
                ('corrosive', models.CharField(choices=[('Sim', 'SIM'), ('Não', 'NÃO'), ('Não Sei', 'NÃO SEI')], max_length=7)),
                ('health_dangerous', models.CharField(choices=[('Sim', 'SIM'), ('Não', 'NÃO'), ('Não Sei', 'NÃO SEI')], max_length=7)),
                ('pollutant', models.CharField(choices=[('Sim', 'SIM'), ('Não', 'NÃO'), ('Não Sei', 'NÃO SEI')], max_length=7)),
                ('can_agitate', models.CharField(choices=[('Sim', 'SIM'), ('Não', 'NÃO'), ('Não Sei', 'NÃO SEI')], max_length=7)),
                ('comments', models.TextField(blank=True)),
                ('generator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labs.MyUser')),
            ],
            options={
                'verbose_name': 'Resíduo',
                'verbose_name_plural': 'Resíduos',
            },
        ),
    ]
