# Generated by Django 2.1.2 on 2018-10-21 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0003_auto_20181021_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='user',
        ),
    ]
